# to build:
# bundle exec jekyll serves
# to update dependency:
# bundle update

# Site
name: "Marco Leong"
title: "Marco Leong's Homepage"
description: "\"For the things we have to learn before we can do them, we learn by doing them\" - Aristotle, The Nicomachean Ethics"
logo: 'assets/images/marco.jpg'
favicon: 'assets/images/marco.jpg'
baseurl: ""
google_analytics: 'UA-138277282-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Marco Leong
    display_name: marco
    # gravatar: 984afb187cbd250785cc40135a18216b
    email: marcoleong.developer@gmail.com
    web: marco-leong.com
    twitter: https://twitter.com/MarcoLeongDev
    description: "iOS and mobile developer with over 10 years professional experience, since 2008. International experiences working in Macau, Singapore and Australia. Fluent in Swift, Obj-C, Dart, C, C++, JS and Typescript, etc"
  

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]